spring.application.name=enrollment-system

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/School
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (Hibernate) Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# OAuth Configuration
spring.security.oauth2.client.registration.google.client-id=141788193913-sg7a5ibfi61ab6hnr9j8kfdqes45f2ov.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.client-name=Google

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub
