spring.application.name=enrollment-system

# Database Configuration
spring.datasource.url=jdbc:postgresql://192.168.68.119:5432/enrollment_system
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (Hibernate) Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
